language: scala
scala:
- 2.11.11
sudo: required
services:
- docker
script:
- ./run.sh
env:
  global:
  - secure: yos7DkRhDiZ3pFVnqznHFxP9pSqcLJNcfhzrHIq2oTzlPMgA/cbIvfqB3Wq4CQJj/DfyNW0gUrd1QG29J3fTqKPpz0MeNLW8KC2YiZWgnzKC1u2C29vRJcA7mhXyKYNrNq2OU8wngjpdkI2VspNLOv9F6mr0pvFiRKK0c4nhmtRB0dyETeOa0w/HxT+bS2yTHvEUVB1CNguZ4w5HOSZpZZ/jads9CEK7cfIFwVBagMZS9VkxuHTlTiNHmutiSoLO81afJMQBOPi6v9Z+pmWsEfx1v7HK2uqzApVQOA6EQtRQB93Lw3s3tVwwQSFApmuTQ4S7jCR6cm7bMcJx7BdqCtqg2OrtaOfAoJPVOzYfECTE8x1QiFtU388xO5rSYgdVqnHafF0Dnd8qeluen400tgjVYbQpH+TkkyADOjpWe0I8X1CUjHDHlKBeY5Mdo9+bVJz4vRZiDE0y4DNs4hrlgrqBcvgUHflS1OOT0YuG7c5QcFykEaVxG1l3ZSMJskhVWybO7w+2KxC75yGeRyggOeIeVOT0lXOZCH0mIQ7nzOkuCGAqBP7e2f9Zq2XB8zi0BCWYaQy3TCtuSuf7HBnL1EQ3s01OLVganTv/sPf6pGZmdjYos8Nw12FKM9g2RxEddHtnFCH4p/CVbcDJQ7kHc/gAiMQ5RYGJaAXoPFWHbdA=
  - secure: OBoN3+oKB3pbVbfvT1pWePY859aGdjY7ivQBXcIrWWZcrby3VEC5Lufqxu2wUDloXM+Upv9iWJ1vf1ytUDBV1KXzKP4o/T8RGfKK35zCH9omuW7e1zGDpOJp60BgSbUKGUGJY/98vLKnu/UFP1s/wbVhhh2yyDZ1D0FQOY8s9p071S97fWQT2NJoLL4CcVsUdgcGLCBO9jdEvGDBp8y/K1meaLx6eThfMYBqUzKUBOmw38qjmIF547ldhyfjlQ0021ShY80EWfUl53qSD5tOddESz/Z5rQQCw8H5MKdfldpmmMuoL3sNTUVKp74Q8+P4gMX/M94o+O0zepps5ATKGL2AZCKxnN+dFpsTMED+lJlRUMh6xg+MZts39FAFryi9Y4rD9FMtMFjhrEmOOh4TdqlJ4OmQllm8YQy5d322sIQvqafdIH5DTQCjLh5R718Nb2aX82wQkwshrSZBYJABKDAHlLcyxPcqVZUVttL6L+iuCy/HFPD2SmCT8/9LiUBDaRVTPY07vpIY5/seZsFiMOy26bsK3EFK+3aSXtm6NFLUzrIw/ScIWkU9vDLZxOcaaNeQM+BfAdes/lMVD4m8c3B9MfJy0Nx0ZEOZa6eAAQm+vz+85nex5+RB86fhiafSaNJ2AZ3glRw5p3jdySPqt1uYMsFykX4DYTsQHR6GGGY=
